// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TopicFiveWebAppMcCoy.Models;

namespace TopicFiveWebAppMcCoy.Migrations.Student
{
    [DbContext(typeof(StudentContext))]
    [Migration("20220710044442_studentinitial")]
    partial class studentinitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TopicFiveWebAppMcCoy.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.ToTable("StudentList");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            FirstName = "Andrew",
                            Grade = "D+",
                            LastName = "McCoy"
                        },
                        new
                        {
                            StudentID = 2,
                            FirstName = "Liam",
                            Grade = "C+",
                            LastName = "Hemsworth"
                        },
                        new
                        {
                            StudentID = 3,
                            FirstName = "Daniel",
                            Grade = "A-",
                            LastName = "Smith"
                        },
                        new
                        {
                            StudentID = 4,
                            FirstName = "Anna",
                            Grade = "B+",
                            LastName = "Cox"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
