// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TopicFiveWebAppMcCoy.Models;

namespace TopicFiveWebAppMcCoy.Migrations.Country
{
    [DbContext(typeof(CountryContext))]
    [Migration("20220713033402_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TopicFiveWebAppMcCoy.Models.Category", b =>
                {
                    b.Property<string>("CategoryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = "indoor",
                            Name = "Indoor"
                        },
                        new
                        {
                            CategoryID = "outdoor",
                            Name = "Outdoor"
                        });
                });

            modelBuilder.Entity("TopicFiveWebAppMcCoy.Models.Country", b =>
                {
                    b.Property<string>("CountryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FlagImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportCategoryID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CountryID");

                    b.HasIndex("GameID");

                    b.HasIndex("SportCategoryID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryID = "canada",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_ca-flag.gif",
                            GameID = "winter",
                            Name = "Canada"
                        },
                        new
                        {
                            CountryID = "sweden",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_sw-flag.gif",
                            GameID = "winter",
                            Name = "Sweden"
                        },
                        new
                        {
                            CountryID = "greatBritain",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_uk-flag.gif",
                            GameID = "winter",
                            Name = "Great Britain"
                        },
                        new
                        {
                            CountryID = "jamaica",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_jm-flag.gif",
                            GameID = "winter",
                            Name = "Jamaica"
                        },
                        new
                        {
                            CountryID = "italy",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_it-flag.gif",
                            GameID = "winter",
                            Name = "Italy"
                        },
                        new
                        {
                            CountryID = "japan",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_ja-flag.gif",
                            GameID = "winter",
                            Name = "Japan"
                        },
                        new
                        {
                            CountryID = "germany",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_gm-flag.gif",
                            GameID = "summer",
                            Name = "Germany"
                        },
                        new
                        {
                            CountryID = "china",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_ch-flag.gif",
                            GameID = "summer",
                            Name = "China"
                        },
                        new
                        {
                            CountryID = "mexico",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_mx-flag.gif-",
                            GameID = "summer",
                            Name = "Mexico"
                        },
                        new
                        {
                            CountryID = "brazil",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_br-flag.gif",
                            GameID = "summer",
                            Name = "Brazil"
                        },
                        new
                        {
                            CountryID = "netherlands",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_nl-flag.gif",
                            GameID = "summer",
                            Name = "Netherlands"
                        },
                        new
                        {
                            CountryID = "usa",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_us-flag.gif",
                            GameID = "summer",
                            Name = "USA"
                        },
                        new
                        {
                            CountryID = "thailand",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_th-flag.gif",
                            GameID = "paralympics",
                            Name = "Thailand"
                        },
                        new
                        {
                            CountryID = "uruguay",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_uy-flag.gif",
                            GameID = "paralympics",
                            Name = "Uruguay"
                        },
                        new
                        {
                            CountryID = "ukraine",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_up-flag.gif",
                            GameID = "paralympics",
                            Name = "Ukraine"
                        },
                        new
                        {
                            CountryID = "austria",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_au-flag.gif",
                            GameID = "paralympics",
                            Name = "Austria"
                        },
                        new
                        {
                            CountryID = "pakistan",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_pk-flag.gif",
                            GameID = "paralympics",
                            Name = "Pakistan"
                        },
                        new
                        {
                            CountryID = "zimbabwe",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_zi-flag.gif",
                            GameID = "paralympics",
                            Name = "Zimbabwe"
                        },
                        new
                        {
                            CountryID = "france",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_fr-flag.gif",
                            GameID = "youth",
                            Name = "France"
                        },
                        new
                        {
                            CountryID = "cyprus",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_cy-flag.gif",
                            GameID = "youth",
                            Name = "Cyprus"
                        },
                        new
                        {
                            CountryID = "russia",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_rs-flag.gif",
                            GameID = "youth",
                            Name = "Russia"
                        },
                        new
                        {
                            CountryID = "finland",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_fi-flag.gif",
                            GameID = "youth",
                            Name = "Finland"
                        },
                        new
                        {
                            CountryID = "slovakia",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_lo-flag.gif",
                            GameID = "youth",
                            Name = "Slovakia"
                        },
                        new
                        {
                            CountryID = "portugal",
                            FlagImage = "https://www.worldometers.info/img/flags/small/tn_po-flag.gif",
                            GameID = "youth",
                            Name = "Portugal"
                        });
                });

            modelBuilder.Entity("TopicFiveWebAppMcCoy.Models.Game", b =>
                {
                    b.Property<string>("GameID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameID");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameID = "winter",
                            Name = "Winter Olympics"
                        },
                        new
                        {
                            GameID = "summer",
                            Name = "Summer Olympics"
                        },
                        new
                        {
                            GameID = "paralympics",
                            Name = "Paralympics"
                        },
                        new
                        {
                            GameID = "youth",
                            Name = "Youth Olymic Games"
                        });
                });

            modelBuilder.Entity("TopicFiveWebAppMcCoy.Models.Country", b =>
                {
                    b.HasOne("TopicFiveWebAppMcCoy.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameID");

                    b.HasOne("TopicFiveWebAppMcCoy.Models.Category", "Sport")
                        .WithMany()
                        .HasForeignKey("SportCategoryID");

                    b.Navigation("Game");

                    b.Navigation("Sport");
                });
#pragma warning restore 612, 618
        }
    }
}
